// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: rc1_before_chart

#include "ui.h"
#include "ui_helpers.h"
#include <lvgl/src/core/lv_disp.h>
#include <lvgl/src/core/lv_obj_pos.h>
#include <lvgl/src/widgets/lv_label.h>

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Header1;
lv_obj_t * ui_Chart1;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Header2;
lv_obj_t * ui_SwitchList;
lv_obj_t * ui_LabelSw1;
lv_obj_t * ui_LabelSw2;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Header3;
lv_obj_t * ui_rollerHour1;
lv_obj_t * ui_rollerHour2;
void ui_event_btnDrawPoint(lv_event_t * e);
lv_obj_t * ui_btnSetTime1;
lv_obj_t * ui_txtBtnSetTime1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1208752757[1] = {&ui_img_657858778};
const lv_img_dsc_t * ui_imgset_rectangle_[1] = {&ui_img_rectangle_59_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void ui_display_pressed_point(lv_obj_t * chart, lv_chart_series_t * series, uint16_t id);

void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // Gesture: Swipe left
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
    // Gesture: Swipe right
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen3_screen_init);
    }

    // Chart pressed 
    if(target == ui_Chart1 && event_code == LV_EVENT_VALUE_CHANGED)
    {
        // Get the current point
        uint32_t pressed_idx =  lv_chart_get_pressed_point(ui_Chart1);
        LV_LOG_USER("Point pressed: %d\n", pressed_idx);
        if(pressed_idx == LV_CHART_POINT_NONE)
            return;
        extern lv_chart_series_t* ui_Chart1_series_1;
        ui_display_pressed_point(ui_Chart1, ui_Chart1_series_1, pressed_idx);

    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_btnDrawPoint(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        plotRoller2();
    }
}


#define USED_CUSTOM_IMPLEMENTATION  1
#if (USED_CUSTOM_IMPLEMENTATION != 0)
void ui_dropdown_custom_init(void);

#endif //(USED_CUSTOM_IMPLEMENTATION != 0)
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    ui_dropdown_custom_init();
    initChartCustom();
}



#define USED_CUSTOM_IMPLEMENTATION  1
#if (USED_CUSTOM_IMPLEMENTATION != 0)
///////////////////// CUSTOM ////////////////////
#define UI_MAX_SCREEN       3

void screen_dropdown_evt_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) 
    {
        int choose_screen = lv_dropdown_get_selected(obj) + 1; // +1 because dropdown index starts at 0
        switch (choose_screen) 
        {
            case 1:
                _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
                break;

            case 2:
                _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
                break;

            case 3:
                _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
                break;

            default:
                // log error
                break;
        }
        
    }
}

void ui_dropdown_custom_init(void)
{
    lv_obj_t* header_component[UI_MAX_SCREEN] = {ui_Header1, ui_Header2, ui_Header3};
    for(int idx=0; idx<UI_MAX_SCREEN; idx++)
    {
        // Get dropdown from header component
        lv_obj_t* dropdown_child = ui_comp_get_child(header_component[idx], UI_COMP_HEADER_MAINDROPDOWN);
        // Set callback for dropdown
        lv_obj_add_event_cb(dropdown_child, screen_dropdown_evt_cb, LV_EVENT_ALL, NULL);
        lv_dropdown_set_text(dropdown_child, "Menu");
    }
}

extern lv_chart_series_t* ui_Chart1_series_1;
void ui_display_pressed_point(lv_obj_t * chart, lv_chart_series_t * series, uint16_t id)
{
        static bool isInit = false;
        static lv_obj_t* label_pressed_point = NULL;
        lv_point_t point;
        lv_chart_get_point_pos_by_id(chart, series, id, &point);
        LV_LOG_USER("Point position: %d, %d\n", point.x, point.y);
        if (!isInit)
        {
            // Create label
            label_pressed_point = lv_label_create(chart);

            // Set label style
            lv_obj_set_style_bg_color(label_pressed_point, lv_color_black(), LV_PART_MAIN);
            lv_obj_set_style_bg_opa(label_pressed_point, LV_OPA_50, LV_PART_MAIN);
            lv_obj_set_width(label_pressed_point, 30);   /// 1
            lv_obj_set_height(label_pressed_point, 20);    /// 1
            //lv_label_set_align(label_pressed_point, LV_ALIGN_CENTER);
            lv_obj_set_style_text_align(label_pressed_point, LV_TEXT_ALIGN_CENTER, 0);
            //lv_obj_set_pos(label_pressed_point, 200, 200);

            isInit = true;
        }
        // Base on the width and height of the label, center the label to the point
        volatile lv_coord_t x_pos = /*chart->coords.x1 + */point.x - 15;
        volatile lv_coord_t y_pos = /*chart->coords.y1 + */point.y - 30;
        //y_pos -= 30;
        // Set label position
        lv_obj_set_pos(label_pressed_point, x_pos, y_pos);
        // Set label text
        lv_label_set_text_fmt(label_pressed_point, "%d", series->y_points[id]);
        
}


#endif //(USED_CUSTOM_IMPLEMENTATION != 0)
