// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: rc1_before_chart

#ifndef _RC1_BEFORE_CHART_UI_H
#define _RC1_BEFORE_CHART_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Header1;
extern lv_obj_t * ui_Chart1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Header2;
extern lv_obj_t * ui_SwitchList;
extern lv_obj_t * ui_LabelSw1;
extern lv_obj_t * ui_LabelSw2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Header3;
extern lv_obj_t * ui_rollerHour1;
extern lv_obj_t * ui_rollerHour2;
void ui_event_btnSetTime1(lv_event_t * e);
extern lv_obj_t * ui_btnSetTime1;
extern lv_obj_t * ui_txtBtnSetTime1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_657858778);    // assets\down-arrow-56.png
LV_IMG_DECLARE(ui_img_rectangle_59_png);    // assets\Rectangle 59.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
