// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: rc1_before_chart

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onBtnSetTime1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
