// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Happy
// Attractive
// Have a great career
// Project name: menu_practice

#include "ui.h"
#include <lvgl/src/misc/lv_color.h>

static const char * mbox_options[] = {"Apply", "Close", ""};

typedef void (*msg_box_callback)(void);
typedef struct
{
	int start_time;
	int end_time;
}time_setting_t;

/*
 * Confirmation message box callback
 * There are only 2 fixed options: "Apply" and "Close"
*/
static void msg_box_confirmation_cb(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_current_target(e);
	// Get selected option
	const char* mbox_selected_btn = lv_msgbox_get_active_btn_text(obj);
    LV_LOG_USER("%s clicked", mbox_selected_btn);
	if(strcmp(mbox_selected_btn, "Apply") == 0)
	{
		// Get the user data and cast to callback function
		msg_box_callback callback = (msg_box_callback)e->user_data;
		if(callback != NULL)
		{
			callback();
		}
	}
	else if(strcmp(mbox_selected_btn, "Close") == 0)
	{
		LV_LOG_USER("Close\n");
	}
	lv_msgbox_close(obj);
}

void confirmation_msg_box_create(const char* msg, msg_box_callback callback)
{
	lv_obj_t * mbox = lv_msgbox_create(NULL, "Confirm action", msg, mbox_options, false);
	lv_obj_add_event_cb(mbox, msg_box_confirmation_cb, LV_EVENT_VALUE_CHANGED, callback);
	lv_obj_center(mbox);	
}

void setRollerTime1(void)
{
	int hour_begin = lv_roller_get_selected(ui_rollerHour1);
	int hour_end = lv_roller_get_selected(ui_rollerHour2);
	LV_LOG_USER("Set time: %d - %d\n", hour_begin, hour_end);
}


void plotRoller2(void);

void onBtnSetTime1(lv_event_t * e)
{
	LV_LOG_USER("onBtnSetTime1\n");
	
    // Create message box
	// confirmation_msg_box_create("SetRollerTime1", setRollerTime1);
	confirmation_msg_box_create("PlotRoller2", plotRoller2);
}



// //////////////////////////////////////// CUSTOM CHART ////////////////////////////////////////
lv_chart_series_t* ui_Chart1_series_1 = NULL;

lv_obj_t * get_ChartCustom(void)
{
	return ui_Chart1;
}



void initChartCustom(void)
{
	ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_palette_main(LV_PALETTE_DEEP_ORANGE), LV_CHART_AXIS_PRIMARY_Y);

    lv_chart_set_all_value(ui_Chart1, ui_Chart1_series_1, 0);
    lv_chart_refresh(ui_Chart1);
}

/**
 * @brief Plotting data based on Roller2 value
 * 
 */
void plotRoller2(void)
{
	int roller2_value = lv_roller_get_selected(ui_rollerHour2);
	LV_LOG_USER("Roller2 value: %d\n", roller2_value);
	lv_chart_set_next_value(get_ChartCustom(), ui_Chart1_series_1, roller2_value);
	lv_chart_refresh(ui_Chart1);
}
