// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: rc1_before_chart

#include "../ui.h"

void ui_ScreenTest_screen_init(void)
{
    ui_ScreenTest = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
