// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: rc1_before_chart

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header2 = ui_Header_create(ui_Screen2);
    lv_obj_set_x(ui_Header2, 0);
    lv_obj_set_y(ui_Header2, 0);

    lv_label_set_text(ui_comp_get_child(ui_Header2, UI_COMP_HEADER_SCREENNAME), "Screen2");

    ui_SwitchList = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SwitchList, 289);
    lv_obj_set_height(ui_SwitchList, 152);
    lv_obj_set_x(ui_SwitchList, -1);
    lv_obj_set_y(ui_SwitchList, 20);
    lv_obj_set_align(ui_SwitchList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SwitchList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SwitchList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SwitchList, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSw1 = ui_LabelSw_create(ui_SwitchList);
    lv_obj_set_x(ui_LabelSw1, -32);
    lv_obj_set_y(ui_LabelSw1, -11);

    lv_textarea_set_text(ui_comp_get_child(ui_LabelSw1, UI_COMP_LABELSW_SWLABEL), "Control 1");

    ui_LabelSw2 = ui_LabelSw_create(ui_SwitchList);
    lv_obj_set_x(ui_LabelSw2, -32);
    lv_obj_set_y(ui_LabelSw2, 1);

    lv_textarea_set_text(ui_comp_get_child(ui_LabelSw2, UI_COMP_LABELSW_SWLABEL), "Control 2");

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
