// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: rc1_before_chart

#include "../ui.h"
#include <lvgl/src/core/lv_event.h>
#include <ui_sample/ui.h>


void ui_event_btnSetTime1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        plotRoller2();
    }

}



void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);

    ui_Header1 = ui_Header_create(ui_Screen1);
    lv_obj_set_x(ui_Header1, 0);
    lv_obj_set_y(ui_Header1, 0);

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 200);
    lv_obj_set_height(ui_Chart1, 100);
    lv_obj_set_x(ui_Chart1, -2);
    lv_obj_set_y(ui_Chart1, 3);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_Chart1, 3, 0);
    lv_chart_set_zoom_x(ui_Chart1, 256);
    lv_chart_set_zoom_y(ui_Chart1, 256);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 3, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 50);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

    // Testing button
    lv_obj_t*ui_btnDrawPoint = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnDrawPoint, 50);
    lv_obj_set_height(ui_btnDrawPoint, 30);
    lv_obj_set_x(ui_btnDrawPoint, 0);
    lv_obj_set_y(ui_btnDrawPoint, 100);
    lv_obj_set_align(ui_btnDrawPoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDrawPoint, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnDrawPoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnDrawPoint, lv_color_hex(0x08DE10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDrawPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_btnDrawPoint, ui_event_btnSetTime1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Chart1, ui_event_Screen1, LV_EVENT_ALL,NULL);

}
